title: CUHK Robotics
description: CUHK Robotics Team Knowledge Base
theme: just-the-docs

url: https://CUHK-Robocon.github.io/knowledge-base

color_scheme: dark

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
